/* 
 * File:   Animations.hpp
 * Author: Koncord <koncord at rwa.su>
 *
 * Created on 4 Февраль 2015 г., 19:41
 */

#ifndef ANIMATIONS_HPP
#define	ANIMATIONS_HPP

enum ANIM_ATTACK
{
	AttackLeft = 26,
	AttackLeftUp,
	AttackLeftDown,
	AttackLeftIS,
	AttackLeftISUp,
	AttackLeftISDown,
	AttackRight,
	AttackRightUp,
	AttackRightDown,
	AttackRightIS,
	AttackRightISUp,
	AttackRightISDown,
	Attack3,
	Attack3Up,
	Attack3Down,
	Attack3IS,
	Attack3ISUp,
	Attack3ISDown,
	Attack4,
	Attack4Up,
	Attack4Down,
	Attack4IS,
	Attack4ISUp,
	Attack4ISDown,
	Attack5,
	Attack5Up,
	Attack5Down,
	Attack5IS,
	Attack5ISUp,
	Attack5ISDown,
	Attack6,
	Attack6Up,
	Attack6Down,
	Attack6IS,
	Attack6ISUp,
	Attack6ISDown,
	Attack7,
	Attack7Up,
	Attack7Down,
	Attack7IS,
	Attack7ISUp,
	Attack7ISDown,
	Attack8,
	Attack8Up,
	Attack8Down,
	Attack8IS,
	Attack8ISUp,
	Attack8ISDown,
	AttackLoop,
	AttackLoopUp,
	AttackLoopDown,
	AttackLoopIS,
	AttackLoopISUp,
	AttackLoopISDown,
	AttackSpin,
	AttackSpinUp,
	AttackSpinDown,
	AttackSpinIS,
	AttackSpinISUp,
	AttackSpinISDown,
	AttackSpin2,
	AttackSpin2Up,
	AttackSpin2Down,
	AttackSpin2IS,
	AttackSpin2ISUp,
	AttackSpin2ISDown,
	AttackPower,
	AttackForwardPower,
	AttackBackPower,
	AttackLeftPower,
	AttackRightPower,
	PlaceMine,
	PlaceMineUp,
	PlaceMineDown,
	PlaceMineIS,
	PlaceMineISUp,
	PlaceMineISDown,
	PlaceMine2,
	PlaceMine2Up,
	PlaceMine2Down,
	PlaceMine2IS,
	PlaceMine2ISUp,
	PlaceMine2ISDown,
	AttackThrow,
	AttackThrowUp,
	AttackThrowDown,
	AttackThrowIS,
	AttackThrowISUp,
	AttackThrowISDown,
	AttackThrow2,
	AttackThrow2Up,
	AttackThrow2Down,
	AttackThrow2IS,
	AttackThrow2ISUp,
	AttackThrow2ISDown,
	AttackThrow3,
	AttackThrow3Up,
	AttackThrow3Down,
	AttackThrow3IS,
	AttackThrow3ISUp,
	AttackThrow3ISDown,
	AttackThrow4,
	AttackThrow4Up,
	AttackThrow4Down,
	AttackThrow4IS,
	AttackThrow4ISUp,
	AttackThrow4ISDown,
	AttackThrow5,
	AttackThrow5Up,
	AttackThrow5Down,
	AttackThrow5IS,
	AttackThrow5ISUp,
	AttackThrow5ISDown,
	PipBoy = 167,
	PipBoyChild = 178,
	ANY = 255
}

#endif	/* ANIMATIONS_HPP */

